# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b21c94facc1928fdb8ddd9c64a81cb10"
name = "future-trust"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products,write_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
